### ISSUE TITLE
Make CI pipelines the same across projects

### ISSUE THREAD

**Issue by stevenbal** [maykinmedia/open-api-framework#13]
Not sure if this repo is the right place for this issue, but I noticed that Open Zaak has an `image_scan` job in the CI pipeline: https://github.com/open-zaak/open-zaak/blob/main/.github/workflows/ci.yml#L268. Is this something we want in the other projects as well?

In general, I think it is a good idea to check if the pipelines are the same (or at least as close as possible) and up to date when it comes to versions for actions

* [ ] Add the best things to the default project - api folder.
* [ ] Make sure all the API projects have similar CI pipelines

**Comment by stevenbal** [comment]
Maybe we could make use of https://github.com/maykinmedia/setup-django-backend/tree/v1.3

**Comment by SonnyBA** [comment]
A first effort to make the CI pipelines more consistent was made through [open-zaak/#1730](https://github.com/open-zaak/open-zaak/pull/1730). The [code quality workflow](https://github.com/open-zaak/open-zaak/actions/runs/10214246797) was used for this and now reuses the code quality workflow from the [open-api-workflows repository](https://github.com/maykinmedia/open-api-workflows/blob/initial-setup/.github/workflows/code-quality.yml).

**Comment by SonnyBA** [comment]
Moving the workflow files to the root repository does not seem possible (screenshot taken from an open-zaak run):


![Image](https://github.com/user-attachments/assets/40c13aa5-169a-4e2f-951e-94356d847bb2)

**Comment by SonnyBA** [comment]
- [ ] Open-zaak
  - https://github.com/open-zaak/open-zaak/pull/1730
- [ ] Open-Klant
- [ ] Referentielijsten
- [ ] Objects-API
- [ ] Objecttypes-API
- [ ] Open-Notificaties
