### ISSUE TITLE
Github repo als template a la community-repository? 

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-api-framework#16]
-> Github repo als template a la community-repository? (Github workflows + basisstructuur, README, license, security.txt, 'components' dir)

Boilerplate repo voor nieuwe registratiecomponenten.

Vraag is of dit in open-api-framework moet zijn of dat we een open-api-framework-startproject oid willen hebben

**Comment by joeribekker** [comment]
Thought about it, tried it, but `django startproject` is much more flexible and powerful to replace texts.
