### ISSUE TITLE
Show version of the release in the admin

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-api-framework#21]
This is something Open Zaak has and is quite useful when reviewing issues in order to determine (using a screenshot of the environment) which version a customer has installed. Showing the version number in the admin (after being logged in) can avoid a bit of back-and-forth.

* [x] Open Zaak
* [ ] Open Notificaties
* [ ] Objects API
* [ ] Objecttypes API
* [ ] Open Klant
* [ ] Referentielijsten API

**Comment by stevenbal** [comment]
@SonnyBA I merged your PR to add this in OAF and added it to 0.5.0, so the git dependencies can be replaced with 0.5.0 in your PRs

**Comment by SonnyBA** [comment]
Thanks @stevenbal, all PR's should be pinned correctly now
