### ISSUE TITLE
Ensure HTTP headers for CSP and HSTS are properly set for the admin

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-api-framework#42]
### Product versie / Product version

1.12 (OZ)

### Omschrijf het probleem / Describe the bug

Taiga AMS 18

CSP headers should be set for the admin (see the Open Forms settings)
HSTS headers should be set for the admin and the API (minimum of 1 year, see the Open Forms settings)

After this has been done ensure new releases have been done for OZ+ON+Obj+OT

**Comment by alextreme** [comment]
@Coperh Thanks and this looks good. I see that I overlooked that also the Cache Control header is to be set. This doesn't have to be set for the admin, but may be missing from the APIs if I see the Taiga issue. It could however also be a missing header on the AMS gateway. Please confirm or deny this and I'll communicate this back

**Comment by Coperh** [comment]
Added in:
- [ ] Open-Zaak  
- [ ] Open-notifcaities
- [ ] Open-Klant
- [x] Objects-API  maykinmedia/objects-api#438
- [x] OjectTypes-API maykinmedia/objecttypes-api#124
- [ ] Referentielijten
