### ISSUE TITLE
OAf Celery settings do not allow CELERY_BROKER_URL to be different from CELERY_RESULT_BACKEND

### ISSUE THREAD

**Issue by stevenbal** [maykinmedia/open-api-framework#48]
### Product versie / Product version

latest / 44eb847

### Omschrijf het probleem / Describe the bug

When implementing the generic base settings in Open API Framework, I took the Celery settings from [Open Zaak](https://github.com/open-zaak/open-zaak/blob/c2ced7cbf81722ac5e88bfa90b5e7db5506b890b/src/openzaak/conf/includes/base.py#L702-L705). There only the value of the envvar ``CELERY_RESULT_BACKEND`` is used for the  ``CELERY_BROKER_URL`` and ``CELERY_RESULT_BACKEND`` settings.

However, in Objects API and Open Notificaties, there were separate envvars for this: 
- https://github.com/maykinmedia/objects-api/blob/b2e586e4363ee59cb284e7cf4c07a25da95930e5/src/objects/conf/base.py#L496-L500
- https://github.com/open-zaak/open-notificaties/blob/37ad034e4675047db35ba326487b58a03c5fdb9e/src/nrc/conf/includes/base.py#L556-L558

This means that Objects API and Open Notificaties lost the ``CELERY_BROKER_URL`` and the possibility to configure these separately

### Verwacht gedrag / Expected behavior

I'm not sure if these were ever set to different values in practice, but I think it would be best to modify the settings such that ``CELERY_BROKER_URL`` can be specified via its own envvar and if it is not specified to fall back on the value of ``CELERY_RESULT_BACKEND``

**Comment by joeribekker** [comment]
Good observation but lets wait until someone in the field reports this as an issue.
