### ISSUE TITLE
Add Cache Control header to API responses?

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-api-framework#57]
### Thema / Theme

API

### Omschrijving / Description

Taiga Amsterdam 18

Continuation of:
https://github.com/maykinmedia/open-api-framework/issues/42

Thanks and this looks good. I see that I overlooked that also the Cache Control header is to be set. This doesn't have to be set for the admin, but may be missing from the APIs if I see the Taiga issue. It could however also be a missing header on the AMS gateway. Please confirm or deny this and I'll communicate this back

**Comment by Coperh** [comment]
Django will add add cache-control headers if you cache a view or cache the whole site (see #58)  

I'm not sure if this is the behaviour Amsterdam wants.

**Comment by alextreme** [comment]
Based on how our APIs work, I would recommend to set a 'no-cache' Cache Control header:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by alextreme** [comment]
Closing here as we're going to solve this via the helm charts: https://github.com/maykinmedia/charts/issues/123
