### ISSUE TITLE
Update django to 4.2

### ISSUE THREAD

**Issue by stevenbal** [maykinmedia/open-api-framework#8]

**Comment by alextreme** [comment]
Mag opgepakt worden ter voorbereiding op https://github.com/maykinmedia/objects-api/pull/358

**Comment by joeribekker** [comment]
First, all projects need to migrate. The status is kept in #12 

In the future, we might need to use versioning, like:

1.x stays on Django 4.2, and only gets the REALLY important updates
2.x introduces Django 5.2 and all projects can then move to use this.

**Comment by stevenbal** [comment]
open api framework already uses django>=4.2: https://github.com/maykinmedia/open-api-framework/blob/main/pyproject.toml#L30, so I think this issue can be closed
